project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs
  preview:
    port: 4200

website:
  page-footer:
    left: |
      Todo el contenido está licenciado bajo ([CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.es)).
    right: 
      - icon: rss
        href: https://aprendetidyverse.com/index.xml
      - icon: twitter
        href: https://twitter.com/dev_aguero
      - icon: instagram
        href: https://www.instagram.com/aprende.tidyverse/
      - icon: facebook
        href: https://www.facebook.com/aprende.tidyverse
      - icon: linkedin
        href: https://www.linkedin.com/in/carlos-aguero-cr/
  open-graph:
    locale: es_ES
    site-name: aprendetidyverse.com
  twitter-card:
    creator: "@dev_aguero"
    site: "@dev_aguero"
  title: "Aprende Tidyverse"
  favicon: favicon.ico
  navbar:
    fixed:
    logo: img/logo.png
    logo-alt: ""
    title: false
    background: white
    right:
      - text: "Inicio"
        file: index.qmd
      - text: "Blog"
        file: posts.qmd
      - text: "Cursos"
        file: courses/index.qmd
  site-url: https://aprendetidyverse.com


format:
  html:
    theme: seem.scss
    include-after-body: plausible.html
    metadata:
      toc: false

      
metadata-files:
  - drafts.yml
