project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs
  preview:
    port: 4200

website:
  search: false
  announcement: 
    content: "**Curso Gratis** - Fundamentos de R y RStudio, inicio de clases 13 de junio [¡Matricúlate aquí!]()" 
    position: below-navbar
    type: warning
    icon: gift
  page-footer:
    left: |
      Todo el contenido está licenciado bajo una licencia ([CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.es)).
    right: 
      - icon: twitter
        href: https://twitter.com/dev_aguero
      - icon: instagram
        href: https://www.instagram.com/aprende.tidyverse/
      - icon: facebook
        href: https://www.facebook.com/aprende.tidyverse
      - icon: linkedin
        href: https://www.linkedin.com/in/carlos-aguero-cr/
  bread-crumbs: true
  open-graph:
    locale: es_ES
    site-name: aprendetidyverse.com
  twitter-card:
    creator: "@dev_aguero"
    site: "@dev_aguero"
  title: "Aprende Tidyverse"
  favicon: favicon.ico
  navbar:
    logo: images/logo.png
    logo-alt: ""
    title: false
    background: white
    left:
      - text: "Blog"
        file: index.qmd
      - text: "Cursos"
        menu:
          - text: "Fundamentos de R y Rstudio **(gratis)**"
            icon: "bi-laptop"
            href: courses/fundamentos_R.qmd
      - text: Proyectos
        file: projects.qmd
      - text: TILs
        file: posts.qmd
    right: 
      - icon: rss
        href: https://aprendetidyverse.com/index.xml
  site-url: https://aprendetidyverse.com


format:
  html:
    theme: seem.scss
    highlight-style: seem.theme
    include-after-body: plausible.html
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      title-block-banner: false
      toc: false
      title-block-categories: false
      toc-depth: 5
      
metadata-files:
  - drafts.yml
