---
pagetitle: Aprende Tidyverse
lang: "es"
toc: false
page-layout: full
---

<h1>Hola, soy <span class="nombre-resaltado">Carlos Ag칲ero B.</span></h1>

Soy Ingeniero de Software. Desde 2015 me dedico a programar en R y a capacitar personas en este campo. Como [instructor certificado por RStudio](https://education.rstudio.com/trainers) para ense침ar Tidyverse y Shiny y por [Software Carpentries](https://carpentries.org/community/instructors/) para la ense침anza de la programaci칩n, he colaborado en la formaci칩n de equipos de ciencia de datos en universidades, sector p칰blico y empresas privadas en toda Am칠rica Latina.

Este proyecto busca ofrecerle contenido gratuito en espa침ol para acompa침arle en su aprendizaje de R y, especialmente, de [tidyverse](https://www.tidyverse.org/).
Espero que encuentre aqu칤 los recursos que necesita.

**Si tiene alg칰n tema espec칤fico que quiera que explique**, puede sugerirlo en este [enlace](). Estoy para ayudarle en su proceso de aprendizaje.

<br>

::: {.grid}

::: {.g-col-12 .g-col-md-4}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<p class="card-text">Inicie en el mundo de R desde cero en este curso de 6 semanas <strong>totalmente gratis</strong>, clases en vivo (Zoom) y sesiones de pr치ctica.</p>
<div style="margin-top: auto;"><a href="about.qmd" class="card-link heading-font">游꾸 Curso Introductorio</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-4}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<p class="card-text">Si desea avanzar en su aprendizaje, puede tomar cursos a un precio accesible con clases en vivo y tutor칤as individuales.</p>
<div style="margin-top: auto;"><a href="posts.qmd" class="card-link second-color-link heading-font">Cursos Avanzados</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-4}
<div class="card h-100" id="card-third-color">
<div class="card-body d-flex flex-column">
<p class="card-text">Una forma de aprender a su ritmo es con nuestra serie de tutoriales, ejemplos concretos de c칩mo resolver problemas comunes.</p>
<div style="margin-top: auto;"><a href="talks.qmd" class="card-link third-color-link heading-font">Tutoriales</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-4}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<p class="card-text">Este es un experimento, pero nuestro objetivo es grabar ejemplos en video para todas las funciones de los paquetes del tidyverse, explicando su uso y c칩mo se relacionan entre ellas.</p>
<div style="margin-top: auto;"><a href="packages.qmd" class="card-link second-color-link heading-font">Documentaci칩n explicada</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-4}
<div class="card h-100" id="card-third-color">
<div class="card-body d-flex flex-column">
<p class="card-text">Si necesita ayuda con un proyecto en espec칤fico, programemos una reuni칩n y resolv치moslo juntos.</p>
<div style="margin-top: auto;"><a href="community.qmd" class="card-link third-color-link heading-font">Tutorias Privadas</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-4}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<p class="card-text">Si tiene alguna propuesta de proyecto o necesita cotizar un curso en particular, puede contactarme a trav칠s de este enlace.</p>
<div style="margin-top: auto;"><a href="contact.qmd" class="card-link heading-font">Contacto (WhatsApp)</a></div>
</div>
</div>
:::

:::
