---
pagetitle: Aprende Tidyverse
lang: "es"
toc: false
page-layout: full
---

<h1><span class="nombre-resaltado">Documentación Explicada</span></h1>

Este es un experimento, pero nuestro objetivo es grabar ejemplos en video para todas las funciones de los paquetes del tidyverse, explicando su uso y cómo se relacionan entre ellas.


::: {.grid}

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>ggplot2</h3>
<p class="card-text">Crea visualizaciones profesionales con la gramática de gráficos personaliza capas, escalas y temas fácilmente.</p>
<ul class="gg-list">
<li><a class = 'enabled' href="ggplot2/ggplot.qmd">ggplot( ) / aes( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_col.qmd">geom_col( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_bar.qmd">geom_bar( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_line.qmd">geom_line( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_point.qmd">geom_point( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_histogram.qmd">geom_histogram( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_density.qmd">geom_density( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_boxplot.qmd">geom_boxplot( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_hline.qmd">geom_hline( )</a></li>
<li><a class = 'enabled' href="ggplot2/geom_vline.qmd">geom_vline( )</a></li>
<li><a class = 'enabled' href="ggplot2/ggsave.qmd">ggsave( )</a></li>
<li><a href="ggplot2/geom_polygon.qmd">geom_polygon( )</a></li>
<li><a href="ggplot2/geom_area.qmd">geom_area( )</a></li>
<li><a href="ggplot2/geom_smooth.qmd">geom_smooth( )</a></li>
<li><a href="ggplot2/geom_text.qmd">geom_text( )</a></li>
<li><a href="ggplot2/geom_rect.qmd">geom_rect( )</a></li>
<li><a href="ggplot2/geom_tile.qmd">geom_tile( )</a></li>
<li><a href="ggplot2/geom_violin.qmd">geom_violin( )</a></li>
<li><a href="ggplot2/coord_sf.qmd">coord_sf( )</a></li>
<li><a href="ggplot2/geom_sf.qmd">geom_sf( )</a></li>
<li><a href="ggplot2/geom_sf_text.qmd">geom_sf_text( )</a></li>
<li><a href="ggplot2/after_stat.qmd">after_stat( )</a></li>
<li><a href="ggplot2/after_scale.qmd">after_scale( )</a></li>
<li><a href="ggplot2/stage.qmd">stage( )</a></li>
<li><a href="ggplot2/position_dodge.qmd">position_dodge( )</a></li>
<li><a href="ggplot2/position_identity.qmd">position_identity( )</a></li>
<li><a href="ggplot2/position_stack.qmd">position_stack( )</a></li>
<li><a href="ggplot2/position_fill.qmd">position_fill( )</a></li>
<li><a href="ggplot2/annotate.qmd">annotate( )</a></li>
<li><a href="ggplot2/annotation_map.qmd">annotation_map( )</a></li>
<li><a href="ggplot2/borders.qmd">borders( )</a></li>
<li><a href="ggplot2/labs.qmd">labs( )</a></li>
<li><a href="ggplot2/expand_limits.qmd">expand_limits( )</a></li>
<li><a href="ggplot2/expansion.qmd">expansion( )</a></li>
<li><a href="ggplot2/expand_scale.qmd">expand_scale( )</a></li>
<li><a href="ggplot2/scale_alpha.qmd">scale_alpha( )</a></li>
<li><a href="ggplot2/scale_alpha_continuous.qmd">scale_alpha_continuous( )</a></li>
<li><a href="ggplot2/scale_color_brewer.qmd">scale_color_brewer( )</a></li>
<li><a href="ggplot2/scale_color_distiller.qmd">scale_color_distiller( )</a></li>
<li><a href="ggplot2/scale_color_continuous.qmd">scale_color_continuous( )</a></li>
<li><a href="ggplot2/scale_color_binned.qmd">scale_color_binned( )</a></li>
<li><a href="ggplot2/scale_color_discrete.qmd">scale_color_discrete( )</a></li>
<li><a href="ggplot2/scale_x_continuous.qmd">scale_x_continuous( )</a></li>
<li><a href="ggplot2/scale_x_log10.qmd">scale_x_log10( )</a></li>
<li><a href="ggplot2/scale_x_reverse.qmd">scale_x_reverse( )</a></li>
<li><a href="ggplot2/scale_x_sqrt.qmd">scale_x_sqrt( )</a></li>
<li><a href="ggplot2/scale_x_date.qmd">scale_x_date( )</a></li>
<li><a href="ggplot2/scale_x_datetime.qmd">scale_x_datetime( )</a></li>
<li><a href="ggplot2/scale_x_time.qmd">scale_x_time( )</a></li>
<li><a href="ggplot2/scale_x_discrete.qmd">scale_x_discrete( )</a></li>
<li><a href="ggplot2/scale_color_gradient.qmd">scale_color_gradient( )</a></li>
<li><a href="ggplot2/scale_color_gradient2.qmd">scale_color_gradient2( )</a></li>
<li><a href="ggplot2/scale_color_gradientn.qmd">scale_color_gradientn( )</a></li>
</ul>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<h3>dplyr</h3>
<p class="card-text">Transforma y resume tablas con verbos expresivos: filter, select, mutate, summarise y joins eficientes.</p>
<ul class="dplyr-list">
<li><a href="dplyr/glimpse.qmd">glimpse( )</a></li>
<li><a href="dplyr/filter.qmd">filter( )</a></li>
<li><a href="dplyr/between.qmd">between( )</a></li>
<li><a href="dplyr/arrange.qmd">arrange( )</a></li>
<li><a href="dplyr/select.qmd">select( )</a></li>
<li><a href="dplyr/distinct.qmd">distinct( )</a></li>
<li><a href="dplyr/slice.qmd">slice( )</a></li>
<li><a href="dplyr/slice_head.qmd">slice_head( )</a></li>
<li><a href="dplyr/slice_tail.qmd">slice_tail( )</a></li>
<li><a href="dplyr/slice_min.qmd">slice_min( )</a></li>
<li><a href="dplyr/slice_max.qmd">slice_max( )</a></li>
<li><a href="dplyr/slice_sample.qmd">slice_sample( )</a></li>
<li><a href="dplyr/dplyr_by.qmd">dplyr_by( )</a></li>
<li><a href="dplyr/group_by.qmd">group_by( )</a></li>
<li><a href="dplyr/ungroup.qmd">ungroup( )</a></li>
<li><a href="dplyr/count.qmd">count( )</a></li>
<li><a href="dplyr/summarise.qmd">summarise( )</a></li>
<li><a href="dplyr/n.qmd">n( )</a></li>
<li><a href="dplyr/mutate.qmd">mutate( )</a></li>
<li><a href="dplyr/case_match.qmd">case_match( )</a></li>
<li><a href="dplyr/case_when.qmd">case_when( )</a></li>
<li><a href="dplyr/relocate.qmd">relocate( )</a></li>
<li><a href="dplyr/pull.qmd">pull( )</a></li>
<li><a href="dplyr/rename.qmd">rename( )</a></li>
<li><a href="dplyr/rename_with.qmd">rename_with( )</a></li>
<li><a href="dplyr/tally.qmd">tally( )</a></li>
<li><a href="dplyr/add_count.qmd">add_count( )</a></li>
<li><a href="dplyr/add_tally.qmd">add_tally( )</a></li>
<li><a href="dplyr/rowwise.qmd">rowwise( )</a></li>
<li><a href="dplyr/reframe.qmd">reframe( )</a></li>
<li><a href="dplyr/cur_group.qmd">cur_group( )</a></li>
<li><a href="dplyr/cur_group_id.qmd">cur_group_id( )</a></li>
<li><a href="dplyr/cur_group_rows.qmd">cur_group_rows( )</a></li>
<li><a href="dplyr/cur_column.qmd">cur_column( )</a></li>
<li><a href="dplyr/bind_cols.qmd">bind_cols( )</a></li>
<li><a href="dplyr/bind_rows.qmd">bind_rows( )</a></li>
<li><a href="dplyr/intersect.qmd">intersect( )</a></li>
<li><a href="dplyr/union.qmd">union( )</a></li>
<li><a href="dplyr/union_all.qmd">union_all( )</a></li>
<li><a href="dplyr/setdiff.qmd">setdiff( )</a></li>
<li><a href="dplyr/setequal.qmd">setequal( )</a></li>
<li><a href="dplyr/symdiff.qmd">symdiff( )</a></li>
<li><a href="dplyr/inner_join.qmd">inner_join( )</a></li>
<li><a href="dplyr/left_join.qmd">left_join( )</a></li>
<li><a href="dplyr/right_join.qmd">right_join( )</a></li>
<li><a href="dplyr/full_join.qmd">full_join( )</a></li>
<li><a href="dplyr/nest_join.qmd">nest_join( )</a></li>
<li><a href="dplyr/semi_join.qmd">semi_join( )</a></li>
<li><a href="dplyr/anti_join.qmd">anti_join( )</a></li>
<li><a href="dplyr/cross_join.qmd">cross_join( )</a></li>
<li><a href="dplyr/join_by.qmd">join_by( )</a></li>
<li><a href="dplyr/rows_insert.qmd">rows_insert( )</a></li>
<li><a href="dplyr/rows_append.qmd">rows_append( )</a></li>
<li><a href="dplyr/rows_update.qmd">rows_update( )</a></li>
<li><a href="dplyr/rows_patch.qmd">rows_patch( )</a></li>
<li><a href="dplyr/rows_upsert.qmd">rows_upsert( )</a></li>
<li><a href="dplyr/rows_delete.qmd">rows_delete( )</a></li>
<li><a href="dplyr/across.qmd">across( )</a></li>
<li><a href="dplyr/if_any.qmd">if_any( )</a></li>
<li><a href="dplyr/if_all.qmd">if_all( )</a></li>
<li><a href="dplyr/c_across.qmd">c_across( )</a></li>
<li><a href="dplyr/pick.qmd">pick( )</a></li>
<li><a href="dplyr/coalesce.qmd">coalesce( )</a></li>
<li><a href="dplyr/consecutive_id.qmd">consecutive_id( )</a></li>
<li><a href="dplyr/cumall.qmd">cumall( )</a></li>
<li><a href="dplyr/cumany.qmd">cumany( )</a></li>
<li><a href="dplyr/cummean.qmd">cummean( )</a></li>
<li><a href="dplyr/desc.qmd">desc( )</a></li>
<li><a href="dplyr/if_else.qmd">if_else( )</a></li>
<li><a href="dplyr/lag.qmd">lag( )</a></li>
<li><a href="dplyr/lead.qmd">lead( )</a></li>
<li><a href="dplyr/n_distinct.qmd">n_distinct( )</a></li>
<li><a href="dplyr/na_if.qmd">na_if( )</a></li>
<li><a href="dplyr/near.qmd">near( )</a></li>
<li><a href="dplyr/nth.qmd">nth( )</a></li>
<li><a href="dplyr/first.qmd">first( )</a></li>
<li><a href="dplyr/last.qmd">last( )</a></li>
<li><a href="dplyr/ntile.qmd">ntile( )</a></li>
<li><a href="dplyr/order_by.qmd">order_by( )</a></li>
<li><a href="dplyr/percent_rank.qmd">percent_rank( )</a></li>
<li><a href="dplyr/cume_dist.qmd">cume_dist( )</a></li>
<li><a href="dplyr/recode.qmd">recode( )</a></li>
<li><a href="dplyr/recode_factor.qmd">recode_factor( )</a></li>
<li><a href="dplyr/row_number.qmd">row_number( )</a></li>
<li><a href="dplyr/min_rank.qmd">min_rank( )</a></li>
<li><a href="dplyr/dense_rank.qmd">dense_rank( )</a></li>
<li><a href="dplyr/group_cols.qmd">group_cols( )</a></li>
<li><a href="dplyr/group_map.qmd">group_map( )</a></li>
<li><a href="dplyr/group_modify.qmd">group_modify( )</a></li>
<li><a href="dplyr/group_walk.qmd">group_walk( )</a></li>
<li><a href="dplyr/group_trim.qmd">group_trim( )</a></li>
<li><a href="dplyr/sample_n.qmd">sample_n( )</a></li>
<li><a href="dplyr/sample_frac.qmd">sample_frac( )</a></li>
<li><a href="dplyr/top_n.qmd">top_n( )</a></li>
<li><a href="dplyr/top_frac.qmd">top_frac( )</a></li>
<li><a href="dplyr/all_vars.qmd">all_vars( )</a></li>
<li><a href="dplyr/any_vars.qmd">any_vars( )</a></li>
<li><a href="dplyr/vars.qmd">vars( )</a></li>
<li><a href="dplyr/with_groups.qmd">with_groups( )</a></li>
<li><a href="dplyr/auto_copy.qmd">auto_copy( )</a></li>
<li><a href="dplyr/compute.qmd">compute( )</a></li>
<li><a href="dplyr/collect.qmd">collect( )</a></li>
<li><a href="dplyr/collapse.qmd">collapse( )</a></li>
<li><a href="dplyr/copy_to.qmd">copy_to( )</a></li>
<li><a href="dplyr/ident.qmd">ident( )</a></li>
<li><a href="dplyr/explain.qmd">explain( )</a></li>
<li><a href="dplyr/show_query.qmd">show_query( )</a></li>
<li><a href="dplyr/tbl.qmd">tbl( )</a></li>
<li><a href="dplyr/is.tbl.qmd">is.tbl( )</a></li>
<li><a href="dplyr/sql.qmd">sql( )</a></li>
</ul>

</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<h3>tidyr</h3>
<p class="card-text">Convierte datos desordenados en formato limpio (tidy).</p>
<ul class="tidyr-list">
<li><a href="packages/tidyr/pivot_longer.qmd">pivot_longer()</a></li>
<li><a href="packages/tidyr/pivot_wider.qmd">pivot_wider()</a></li>
<li><a href="packages/tidyr/unnest_longer.qmd">unnest_longer()</a></li>
<li><a href="packages/tidyr/unnest_wider.qmd">unnest_wider()</a></li>
<li><a href="packages/tidyr/unnest.qmd">unnest()</a></li>
<li><a href="packages/tidyr/hoist.qmd">hoist()</a></li>
<li><a href="packages/tidyr/separate_longer_delim.qmd">separate_longer_delim()</a></li>
<li><a href="packages/tidyr/separate_longer_position.qmd">separate_longer_position()</a></li>
<li><a href="packages/tidyr/separate_wider_delim.qmd">separate_wider_delim()</a></li>
<li><a href="packages/tidyr/separate_wider_position.qmd">separate_wider_position()</a></li>
<li><a href="packages/tidyr/separate_wider_regex.qmd">separate_wider_regex()</a></li>
<li><a href="packages/tidyr/unite.qmd">unite()</a></li>
<li><a href="packages/tidyr/complete.qmd">complete()</a></li>
<li><a href="packages/tidyr/drop_na.qmd">drop_na()</a></li>
<li><a href="packages/tidyr/expand.qmd">expand()</a></li>
<li><a href="packages/tidyr/crossing.qmd">crossing()</a></li>
<li><a href="packages/tidyr/nesting.qmd">nesting()</a></li>
<li><a href="packages/tidyr/expand_grid.qmd">expand_grid()</a></li>
<li><a href="packages/tidyr/fill.qmd">fill()</a></li>
<li><a href="packages/tidyr/full_seq.qmd">full_seq()</a></li>
<li><a href="packages/tidyr/replace_na.qmd">replace_na()</a></li>
<li><a href="packages/tidyr/chop.qmd">chop()</a></li>
<li><a href="packages/tidyr/unchop.qmd">unchop()</a></li>
<li><a href="packages/tidyr/pack.qmd">pack()</a></li>
<li><a href="packages/tidyr/unpack.qmd">unpack()</a></li>
<li><a href="packages/tidyr/uncount.qmd">uncount()</a></li>
<li><a href="packages/tidyr/nest.qmd">nest()</a></li>
<li><a href="packages/tidyr/extract.qmd">extract()</a></li>
<li><a href="packages/tidyr/separate.qmd">separate()</a></li>
<li><a href="packages/tidyr/separate_rows.qmd">separate_rows()</a></li>
</ul>

</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<h3>readr</h3>
<p class="card-text">Importa archivos CSV rápidamente con detección automática de tipos.</p>
<ul class="readr-list">
<li><a href="packages/readr/read_delim.qmd">read_delim()</a></li>
<li><a href="packages/readr/read_csv.qmd">read_csv()</a></li>
<li><a href="packages/readr/read_csv2.qmd">read_csv2()</a></li>
<li><a href="packages/readr/read_tsv.qmd">read_tsv()</a></li>
<li><a href="packages/readr/read_fwf.qmd">read_fwf()</a></li>
<li><a href="packages/readr/fwf_empty.qmd">fwf_empty()</a></li>
<li><a href="packages/readr/fwf_widths.qmd">fwf_widths()</a></li>
<li><a href="packages/readr/fwf_positions.qmd">fwf_positions()</a></li>
<li><a href="packages/readr/fwf_cols.qmd">fwf_cols()</a></li>
<li><a href="packages/readr/read_log.qmd">read_log()</a></li>
<li><a href="packages/readr/read_table.qmd">read_table()</a></li>
<li><a href="packages/readr/problems.qmd">problems()</a></li>
<li><a href="packages/readr/stop_for_problems.qmd">stop_for_problems()</a></li>
<li><a href="packages/readr/cols.qmd">cols()</a></li>
<li><a href="packages/readr/cols_only.qmd">cols_only()</a></li>
<li><a href="packages/readr/cols_condense.qmd">cols_condense()</a></li>
<li><a href="packages/readr/spec.qmd">spec()</a></li>
<li><a href="packages/readr/spec_delim.qmd">spec_delim()</a></li>
<li><a href="packages/readr/spec_csv.qmd">spec_csv()</a></li>
<li><a href="packages/readr/spec_csv2.qmd">spec_csv2()</a></li>
<li><a href="packages/readr/spec_tsv.qmd">spec_tsv()</a></li>
<li><a href="packages/readr/spec_table.qmd">spec_table()</a></li>
<li><a href="packages/readr/parse_logical.qmd">parse_logical()</a></li>
<li><a href="packages/readr/parse_integer.qmd">parse_integer()</a></li>
<li><a href="packages/readr/parse_double.qmd">parse_double()</a></li>
<li><a href="packages/readr/parse_character.qmd">parse_character()</a></li>
<li><a href="packages/readr/col_logical.qmd">col_logical()</a></li>
<li><a href="packages/readr/col_integer.qmd">col_integer()</a></li>
<li><a href="packages/readr/col_double.qmd">col_double()</a></li>
<li><a href="packages/readr/col_character.qmd">col_character()</a></li>
<li><a href="packages/readr/parse_datetime.qmd">parse_datetime()</a></li>
<li><a href="packages/readr/parse_date.qmd">parse_date()</a></li>
<li><a href="packages/readr/parse_time.qmd">parse_time()</a></li>
<li><a href="packages/readr/col_datetime.qmd">col_datetime()</a></li>
<li><a href="packages/readr/col_date.qmd">col_date()</a></li>
<li><a href="packages/readr/col_time.qmd">col_time()</a></li>
<li><a href="packages/readr/parse_factor.qmd">parse_factor()</a></li>
<li><a href="packages/readr/col_factor.qmd">col_factor()</a></li>
<li><a href="packages/readr/parse_guess.qmd">parse_guess()</a></li>
<li><a href="packages/readr/col_guess.qmd">col_guess()</a></li>
<li><a href="packages/readr/guess_parser.qmd">guess_parser()</a></li>
<li><a href="packages/readr/parse_number.qmd">parse_number()</a></li>
<li><a href="packages/readr/col_number.qmd">col_number()</a></li>
<li><a href="packages/readr/col_skip.qmd">col_skip()</a></li>
<li><a href="packages/readr/locale.qmd">locale()</a></li>
<li><a href="packages/readr/default_locale.qmd">default_locale()</a></li>
<li><a href="packages/readr/date_names.qmd">date_names()</a></li>
<li><a href="packages/readr/date_names_lang.qmd">date_names_lang()</a></li>
<li><a href="packages/readr/date_names_langs.qmd">date_names_langs()</a></li>
<li><a href="packages/readr/format_delim.qmd">format_delim()</a></li>
<li><a href="packages/readr/format_csv.qmd">format_csv()</a></li>
<li><a href="packages/readr/format_csv2.qmd">format_csv2()</a></li>
<li><a href="packages/readr/format_tsv.qmd">format_tsv()</a></li>
<li><a href="packages/readr/write_delim.qmd">write_delim()</a></li>
<li><a href="packages/readr/write_csv.qmd">write_csv()</a></li>
<li><a href="packages/readr/write_csv2.qmd">write_csv2()</a></li>
<li><a href="packages/readr/write_excel_csv.qmd">write_excel_csv()</a></li>
<li><a href="packages/readr/write_excel_csv2.qmd">write_excel_csv2()</a></li>
<li><a href="packages/readr/write_tsv.qmd">write_tsv()</a></li>
<li><a href="packages/readr/with_edition.qmd">with_edition()</a></li>
<li><a href="packages/readr/local_edition.qmd">local_edition()</a></li>
<li><a href="packages/readr/edition_get.qmd">edition_get()</a></li>
<li><a href="packages/readr/melt_delim.qmd">melt_delim()</a></li>
<li><a href="packages/readr/melt_csv.qmd">melt_csv()</a></li>
<li><a href="packages/readr/melt_csv2.qmd">melt_csv2()</a></li>
<li><a href="packages/readr/melt_tsv.qmd">melt_tsv()</a></li>
<li><a href="packages/readr/melt_fwf.qmd">melt_fwf()</a></li>
<li><a href="packages/readr/melt_table.qmd">melt_table()</a></li>
<li><a href="packages/readr/melt_table2.qmd">melt_table2()</a></li>
<li><a href="packages/readr/read_file.qmd">read_file()</a></li>
<li><a href="packages/readr/read_file_raw.qmd">read_file_raw()</a></li>
<li><a href="packages/readr/write_file.qmd">write_file()</a></li>
<li><a href="packages/readr/read_lines.qmd">read_lines()</a></li>
<li><a href="packages/readr/read_lines_raw.qmd">read_lines_raw()</a></li>
<li><a href="packages/readr/write_lines.qmd">write_lines()</a></li>
<li><a href="packages/readr/read_rds.qmd">read_rds()</a></li>
<li><a href="packages/readr/write_rds.qmd">write_rds()</a></li>
<li><a href="packages/readr/read_builtin.qmd">read_builtin()</a></li>
<li><a href="packages/readr/count_fields.qmd">count_fields()</a></li>
<li><a href="packages/readr/guess_encoding.qmd">guess_encoding()</a></li>
<li><a href="packages/readr/type_convert.qmd">type_convert()</a></li>
<li><a href="packages/readr/readr_example.qmd">readr_example()</a></li>
<li><a href="packages/readr/clipboard.qmd">clipboard()</a></li>
<li><a href="packages/readr/show_progress.qmd">show_progress()</a></li>
<li><a href="packages/readr/readr_threads.qmd">readr_threads()</a></li>
<li><a href="packages/readr/should_show_types.qmd">should_show_types()</a></li>
<li><a href="packages/readr/should_read_lazy.qmd">should_read_lazy()</a></li>
</ul>

</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>purrr</h3>
<p class="card-text">Aplica funciones sobre listas y data frames con map, reduce, safely y walk, evitando bucles explícitos.</p>
<ul class="purrr-list">
<li><a href="packages/purrr/map.qmd">map()</a></li>
<li><a href="packages/purrr/map_lgl.qmd">map_lgl()</a></li>
<li><a href="packages/purrr/map_int.qmd">map_int()</a></li>
<li><a href="packages/purrr/map_dbl.qmd">map_dbl()</a></li>
<li><a href="packages/purrr/map_chr.qmd">map_chr()</a></li>
<li><a href="packages/purrr/map_vec.qmd">map_vec()</a></li>
<li><a href="packages/purrr/walk.qmd">walk()</a></li>
<li><a href="packages/purrr/as_mapper.qmd">as_mapper()</a></li>
<li><a href="packages/purrr/map_if.qmd">map_if()</a></li>
<li><a href="packages/purrr/map_at.qmd">map_at()</a></li>
<li><a href="packages/purrr/map_depth.qmd">map_depth()</a></li>
<li><a href="packages/purrr/modify_depth.qmd">modify_depth()</a></li>
<li><a href="packages/purrr/map2.qmd">map2()</a></li>
<li><a href="packages/purrr/map2_lgl.qmd">map2_lgl()</a></li>
<li><a href="packages/purrr/map2_int.qmd">map2_int()</a></li>
<li><a href="packages/purrr/map2_dbl.qmd">map2_dbl()</a></li>
<li><a href="packages/purrr/map2_chr.qmd">map2_chr()</a></li>
<li><a href="packages/purrr/map2_vec.qmd">map2_vec()</a></li>
<li><a href="packages/purrr/walk2.qmd">walk2()</a></li>
<li><a href="packages/purrr/pmap.qmd">pmap()</a></li>
<li><a href="packages/purrr/pmap_lgl.qmd">pmap_lgl()</a></li>
<li><a href="packages/purrr/pmap_int.qmd">pmap_int()</a></li>
<li><a href="packages/purrr/pmap_dbl.qmd">pmap_dbl()</a></li>
<li><a href="packages/purrr/pmap_chr.qmd">pmap_chr()</a></li>
<li><a href="packages/purrr/pmap_vec.qmd">pmap_vec()</a></li>
<li><a href="packages/purrr/pwalk.qmd">pwalk()</a></li>
<li><a href="packages/purrr/modify.qmd">modify()</a></li>
<li><a href="packages/purrr/modify_if.qmd">modify_if()</a></li>
<li><a href="packages/purrr/modify_at.qmd">modify_at()</a></li>
<li><a href="packages/purrr/modify2.qmd">modify2()</a></li>
<li><a href="packages/purrr/imodify.qmd">imodify()</a></li>
<li><a href="packages/purrr/modify_tree.qmd">modify_tree()</a></li>
<li><a href="packages/purrr/imap.qmd">imap()</a></li>
<li><a href="packages/purrr/imap_lgl.qmd">imap_lgl()</a></li>
<li><a href="packages/purrr/imap_chr.qmd">imap_chr()</a></li>
<li><a href="packages/purrr/imap_int.qmd">imap_int()</a></li>
<li><a href="packages/purrr/imap_dbl.qmd">imap_dbl()</a></li>
<li><a href="packages/purrr/imap_vec.qmd">imap_vec()</a></li>
<li><a href="packages/purrr/iwalk.qmd">iwalk()</a></li>
<li><a href="packages/purrr/lmap.qmd">lmap()</a></li>
<li><a href="packages/purrr/lmap_if.qmd">lmap_if()</a></li>
<li><a href="packages/purrr/lmap_at.qmd">lmap_at()</a></li>
<li><a href="packages/purrr/detect.qmd">detect()</a></li>
<li><a href="packages/purrr/detect_index.qmd">detect_index()</a></li>
<li><a href="packages/purrr/every.qmd">every()</a></li>
<li><a href="packages/purrr/some.qmd">some()</a></li>
<li><a href="packages/purrr/none.qmd">none()</a></li>
<li><a href="packages/purrr/has_element.qmd">has_element()</a></li>
<li><a href="packages/purrr/head_while.qmd">head_while()</a></li>
<li><a href="packages/purrr/tail_while.qmd">tail_while()</a></li>
<li><a href="packages/purrr/keep.qmd">keep()</a></li>
<li><a href="packages/purrr/discard.qmd">discard()</a></li>
<li><a href="packages/purrr/compact.qmd">compact()</a></li>
<li><a href="packages/purrr/keep_at.qmd">keep_at()</a></li>
<li><a href="packages/purrr/discard_at.qmd">discard_at()</a></li>
<li><a href="packages/purrr/pluck.qmd">pluck()</a></li>
<li><a href="packages/purrr/pluck<-.qmd">pluck&lt;-()</a></li>
<li><a href="packages/purrr/pluck_exists.qmd">pluck_exists()</a></li>
<li><a href="packages/purrr/chuck.qmd">chuck()</a></li>
<li><a href="packages/purrr/pluck_depth.qmd">pluck_depth()</a></li>
<li><a href="packages/purrr/modify_in.qmd">modify_in()</a></li>
<li><a href="packages/purrr/assign_in.qmd">assign_in()</a></li>
<li><a href="packages/purrr/attr_getter.qmd">attr_getter()</a></li>
<li><a href="packages/purrr/accumulate.qmd">accumulate()</a></li>
<li><a href="packages/purrr/accumulate2.qmd">accumulate2()</a></li>
<li><a href="packages/purrr/list_c.qmd">list_c()</a></li>
<li><a href="packages/purrr/list_cbind.qmd">list_cbind()</a></li>
<li><a href="packages/purrr/list_rbind.qmd">list_rbind()</a></li>
<li><a href="packages/purrr/list_flatten.qmd">list_flatten()</a></li>
<li><a href="packages/purrr/list_assign.qmd">list_assign()</a></li>
<li><a href="packages/purrr/list_modify.qmd">list_modify()</a></li>
<li><a href="packages/purrr/list_merge.qmd">list_merge()</a></li>
<li><a href="packages/purrr/list_simplify.qmd">list_simplify()</a></li>
<li><a href="packages/purrr/list_transpose.qmd">list_transpose()</a></li>
<li><a href="packages/purrr/reduce.qmd">reduce()</a></li>
<li><a href="packages/purrr/reduce2.qmd">reduce2()</a></li>
<li><a href="packages/purrr/flatten.qmd">flatten()</a></li>
<li><a href="packages/purrr/flatten_lgl.qmd">flatten_lgl()</a></li>
<li><a href="packages/purrr/flatten_int.qmd">flatten_int()</a></li>
<li><a href="packages/purrr/flatten_dbl.qmd">flatten_dbl()</a></li>
<li><a href="packages/purrr/flatten_chr.qmd">flatten_chr()</a></li>
<li><a href="packages/purrr/flatten_dfr.qmd">flatten_dfr()</a></li>
<li><a href="packages/purrr/flatten_dfc.qmd">flatten_dfc()</a></li>
<li><a href="packages/purrr/map_dfr.qmd">map_dfr()</a></li>
<li><a href="packages/purrr/map_dfc.qmd">map_dfc()</a></li>
<li><a href="packages/purrr/imap_dfr.qmd">imap_dfr()</a></li>
<li><a href="packages/purrr/imap_dfc.qmd">imap_dfc()</a></li>
<li><a href="packages/purrr/map2_dfr.qmd">map2_dfr()</a></li>
<li><a href="packages/purrr/map2_dfc.qmd">map2_dfc()</a></li>
<li><a href="packages/purrr/pmap_dfr.qmd">pmap_dfr()</a></li>
<li><a href="packages/purrr/pmap_dfc.qmd">pmap_dfc()</a></li>
<li><a href="packages/purrr/as_vector.qmd">as_vector()</a></li>
<li><a href="packages/purrr/simplify.qmd">simplify()</a></li>
<li><a href="packages/purrr/simplify_all.qmd">simplify_all()</a></li>
<li><a href="packages/purrr/transpose.qmd">transpose()</a></li>
<li><a href="packages/purrr/auto_browse.qmd">auto_browse()</a></li>
<li><a href="packages/purrr/compose.qmd">compose()</a></li>
<li><a href="packages/purrr/insistently.qmd">insistently()</a></li>
<li><a href="packages/purrr/negate.qmd">negate()</a></li>
<li><a href="packages/purrr/partial.qmd">partial()</a></li>
<li><a href="packages/purrr/possibly.qmd">possibly()</a></li>
<li><a href="packages/purrr/quietly.qmd">quietly()</a></li>
<li><a href="packages/purrr/safely.qmd">safely()</a></li>
<li><a href="packages/purrr/slowly.qmd">slowly()</a></li>
<li><a href="packages/purrr/array_branch.qmd">array_branch()</a></li>
<li><a href="packages/purrr/array_tree.qmd">array_tree()</a></li>
<li><a href="packages/purrr/rate_delay.qmd">rate_delay()</a></li>
<li><a href="packages/purrr/rate_backoff.qmd">rate_backoff()</a></li>
<li><a href="packages/purrr/is_rate.qmd">is_rate()</a></li>
<li><a href="packages/purrr/progress_bars.qmd">progress_bars</a></li>
</ul>

</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>stringr</h3>
<p class="card-text">Manipula texto: busca, extrae, reemplaza y formatea con expresiones regulares (regex).</p>
<ul class="stringr-list">
<li><a href="packages/stringr/str_count.qmd">str_count()</a></li>
<li><a href="packages/stringr/str_detect.qmd">str_detect()</a></li>
<li><a href="packages/stringr/str_escape.qmd">str_escape()</a></li>
<li><a href="packages/stringr/str_extract.qmd">str_extract()</a></li>
<li><a href="packages/stringr/str_extract_all.qmd">str_extract_all()</a></li>
<li><a href="packages/stringr/str_locate.qmd">str_locate()</a></li>
<li><a href="packages/stringr/str_locate_all.qmd">str_locate_all()</a></li>
<li><a href="packages/stringr/str_match.qmd">str_match()</a></li>
<li><a href="packages/stringr/str_match_all.qmd">str_match_all()</a></li>
<li><a href="packages/stringr/str_replace.qmd">str_replace()</a></li>
<li><a href="packages/stringr/str_replace_all.qmd">str_replace_all()</a></li>
<li><a href="packages/stringr/str_remove.qmd">str_remove()</a></li>
<li><a href="packages/stringr/str_remove_all.qmd">str_remove_all()</a></li>
<li><a href="packages/stringr/str_split.qmd">str_split()</a></li>
<li><a href="packages/stringr/str_split_1.qmd">str_split_1()</a></li>
<li><a href="packages/stringr/str_split_fixed.qmd">str_split_fixed()</a></li>
<li><a href="packages/stringr/str_split_i.qmd">str_split_i()</a></li>
<li><a href="packages/stringr/str_starts.qmd">str_starts()</a></li>
<li><a href="packages/stringr/str_ends.qmd">str_ends()</a></li>
<li><a href="packages/stringr/fixed.qmd">fixed()</a></li>
<li><a href="packages/stringr/coll.qmd">coll()</a></li>
<li><a href="packages/stringr/regex.qmd">regex()</a></li>
<li><a href="packages/stringr/boundary.qmd">boundary()</a></li>
<li><a href="packages/stringr/str_subset.qmd">str_subset()</a></li>
<li><a href="packages/stringr/str_which.qmd">str_which()</a></li>
<li><a href="packages/stringr/str_c.qmd">str_c()</a></li>
<li><a href="packages/stringr/str_flatten.qmd">str_flatten()</a></li>
<li><a href="packages/stringr/str_flatten_comma.qmd">str_flatten_comma()</a></li>
<li><a href="packages/stringr/str_glue.qmd">str_glue()</a></li>
<li><a href="packages/stringr/str_glue_data.qmd">str_glue_data()</a></li>
<li><a href="packages/stringr/str_dup.qmd">str_dup()</a></li>
<li><a href="packages/stringr/str_length.qmd">str_length()</a></li>
<li><a href="packages/stringr/str_width.qmd">str_width()</a></li>
<li><a href="packages/stringr/str_pad.qmd">str_pad()</a></li>
<li><a href="packages/stringr/str_sub.qmd">str_sub()</a></li>
<li><a href="packages/stringr/str_sub<-.qmd">str_sub&lt;-()</a></li>
<li><a href="packages/stringr/str_sub_all.qmd">str_sub_all()</a></li>
<li><a href="packages/stringr/str_trim.qmd">str_trim()</a></li>
<li><a href="packages/stringr/str_squish.qmd">str_squish()</a></li>
<li><a href="packages/stringr/str_trunc.qmd">str_trunc()</a></li>
<li><a href="packages/stringr/str_wrap.qmd">str_wrap()</a></li>
<li><a href="packages/stringr/str_order.qmd">str_order()</a></li>
<li><a href="packages/stringr/str_rank.qmd">str_rank()</a></li>
<li><a href="packages/stringr/str_sort.qmd">str_sort()</a></li>
<li><a href="packages/stringr/str_equal.qmd">str_equal()</a></li>
<li><a href="packages/stringr/str_to_upper.qmd">str_to_upper()</a></li>
<li><a href="packages/stringr/str_to_lower.qmd">str_to_lower()</a></li>
<li><a href="packages/stringr/str_to_title.qmd">str_to_title()</a></li>
<li><a href="packages/stringr/str_to_sentence.qmd">str_to_sentence()</a></li>
<li><a href="packages/stringr/str_unique.qmd">str_unique()</a></li>
<li><a href="packages/stringr/invert_match.qmd">invert_match()</a></li>
<li><a href="packages/stringr/str_conv.qmd">str_conv()</a></li>
<li><a href="packages/stringr/str_like.qmd">str_like()</a></li>
<li><a href="packages/stringr/str_replace_na.qmd">str_replace_na()</a></li>
<li><a href="packages/stringr/str_view.qmd">str_view()</a></li>
<li><a href="packages/stringr/word.qmd">word()</a></li>
<li><a href="packages/stringr/sentences.qmd">sentences</a></li>
<li><a href="packages/stringr/fruit.qmd">fruit</a></li>
<li><a href="packages/stringr/words.qmd">words</a></li>
</ul>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>forcats</h3>
<p class="card-text">Simplifica factores: reordena, combina, recodifica y analiza niveles de forma intuitiva.</p>
<ul class="forcats-list">
<li><a href="packages/forcats/fct_relevel.qmd">fct_relevel()</a></li>
<li><a href="packages/forcats/fct_inorder.qmd">fct_inorder()</a></li>
<li><a href="packages/forcats/fct_infreq.qmd">fct_infreq()</a></li>
<li><a href="packages/forcats/fct_inseq.qmd">fct_inseq()</a></li>
<li><a href="packages/forcats/fct_reorder.qmd">fct_reorder()</a></li>
<li><a href="packages/forcats/fct_reorder2.qmd">fct_reorder2()</a></li>
<li><a href="packages/forcats/last2.qmd">last2()</a></li>
<li><a href="packages/forcats/first2.qmd">first2()</a></li>
<li><a href="packages/forcats/fct_shuffle.qmd">fct_shuffle()</a></li>
<li><a href="packages/forcats/fct_rev.qmd">fct_rev()</a></li>
<li><a href="packages/forcats/fct_shift.qmd">fct_shift()</a></li>
<li><a href="packages/forcats/fct_anon.qmd">fct_anon()</a></li>
<li><a href="packages/forcats/fct_collapse.qmd">fct_collapse()</a></li>
<li><a href="packages/forcats/fct_lump.qmd">fct_lump()</a></li>
<li><a href="packages/forcats/fct_lump_min.qmd">fct_lump_min()</a></li>
<li><a href="packages/forcats/fct_lump_prop.qmd">fct_lump_prop()</a></li>
<li><a href="packages/forcats/fct_lump_n.qmd">fct_lump_n()</a></li>
<li><a href="packages/forcats/fct_lump_lowfreq.qmd">fct_lump_lowfreq()</a></li>
<li><a href="packages/forcats/fct_other.qmd">fct_other()</a></li>
<li><a href="packages/forcats/fct_recode.qmd">fct_recode()</a></li>
<li><a href="packages/forcats/fct_relabel.qmd">fct_relabel()</a></li>
<li><a href="packages/forcats/fct_expand.qmd">fct_expand()</a></li>
<li><a href="packages/forcats/fct_drop.qmd">fct_drop()</a></li>
<li><a href="packages/forcats/fct_na_value_to_level.qmd">fct_na_value_to_level()</a></li>
<li><a href="packages/forcats/fct_na_level_to_value.qmd">fct_na_level_to_value()</a></li>
<li><a href="packages/forcats/fct_unify.qmd">fct_unify()</a></li>
<li><a href="packages/forcats/fct_c.qmd">fct_c()</a></li>
<li><a href="packages/forcats/fct_cross.qmd">fct_cross()</a></li>
<li><a href="packages/forcats/fct.qmd">fct()</a></li>
<li><a href="packages/forcats/as_factor.qmd">as_factor()</a></li>
<li><a href="packages/forcats/fct_count.qmd">fct_count()</a></li>
<li><a href="packages/forcats/fct_match.qmd">fct_match()</a></li>
<li><a href="packages/forcats/fct_unique.qmd">fct_unique()</a></li>
<li><a href="packages/forcats/lvls_reorder.qmd">lvls_reorder()</a></li>
<li><a href="packages/forcats/lvls_revalue.qmd">lvls_revalue()</a></li>
<li><a href="packages/forcats/lvls_expand.qmd">lvls_expand()</a></li>
<li><a href="packages/forcats/lvls_union.qmd">lvls_union()</a></li>
<li><a href="packages/forcats/gss_cat.qmd">gss_cat</a></li>
</ul>

</div>
</div>
:::

::: {.g-col-12 .g-col-md-12}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>lubridate</h3>
<p class="card-text">Gestiona fechas y horas: parsea, extrae componentes, realiza aritmética y maneja zonas horarias.</p>
<ul class="lubridate-list">
<li><a href="packages/lubridate/ymd.qmd">ymd()</a></li>
<li><a href="packages/lubridate/ydm.qmd">ydm()</a></li>
<li><a href="packages/lubridate/mdy.qmd">mdy()</a></li>
<li><a href="packages/lubridate/myd.qmd">myd()</a></li>
<li><a href="packages/lubridate/dmy.qmd">dmy()</a></li>
<li><a href="packages/lubridate/dym.qmd">dym()</a></li>
<li><a href="packages/lubridate/yq.qmd">yq()</a></li>
<li><a href="packages/lubridate/ym.qmd">ym()</a></li>
<li><a href="packages/lubridate/my.qmd">my()</a></li>
<li><a href="packages/lubridate/ymd_hms.qmd">ymd_hms()</a></li>
<li><a href="packages/lubridate/ymd_hm.qmd">ymd_hm()</a></li>
<li><a href="packages/lubridate/ymd_h.qmd">ymd_h()</a></li>
<li><a href="packages/lubridate/dmy_hms.qmd">dmy_hms()</a></li>
<li><a href="packages/lubridate/dmy_hm.qmd">dmy_hm()</a></li>
<li><a href="packages/lubridate/dmy_h.qmd">dmy_h()</a></li>
<li><a href="packages/lubridate/mdy_hms.qmd">mdy_hms()</a></li>
<li><a href="packages/lubridate/mdy_hm.qmd">mdy_hm()</a></li>
<li><a href="packages/lubridate/mdy_h.qmd">mdy_h()</a></li>
<li><a href="packages/lubridate/ydm_hms.qmd">ydm_hms()</a></li>
<li><a href="packages/lubridate/ydm_hm.qmd">ydm_hm()</a></li>
<li><a href="packages/lubridate/ydm_h.qmd">ydm_h()</a></li>
<li><a href="packages/lubridate/ms.qmd">ms()</a></li>
<li><a href="packages/lubridate/hm.qmd">hm()</a></li>
<li><a href="packages/lubridate/hms.qmd">hms()</a></li>
<li><a href="packages/lubridate/parse_date_time.qmd">parse_date_time()</a></li>
<li><a href="packages/lubridate/parse_date_time2.qmd">parse_date_time2()</a></li>
<li><a href="packages/lubridate/fast_strptime.qmd">fast_strptime()</a></li>
<li><a href="packages/lubridate/guess_formats.qmd">guess_formats()</a></li>
<li><a href="packages/lubridate/year.qmd">year()</a></li>
<li><a href="packages/lubridate/year<-.qmd">year&lt;-()</a></li>
<li><a href="packages/lubridate/isoyear.qmd">isoyear()</a></li>
<li><a href="packages/lubridate/epiyear.qmd">epiyear()</a></li>
<li><a href="packages/lubridate/quarter.qmd">quarter()</a></li>
<li><a href="packages/lubridate/semester.qmd">semester()</a></li>
<li><a href="packages/lubridate/month.qmd">month()</a></li>
<li><a href="packages/lubridate/month<-.qmd">month&lt;-()</a></li>
<li><a href="packages/lubridate/week.qmd">week()</a></li>
<li><a href="packages/lubridate/week<-.qmd">week&lt;-()</a></li>
<li><a href="packages/lubridate/isoweek.qmd">isoweek()</a></li>
<li><a href="packages/lubridate/epiweek.qmd">epiweek()</a></li>
<li><a href="packages/lubridate/day.qmd">day()</a></li>
<li><a href="packages/lubridate/mday.qmd">mday()</a></li>
<li><a href="packages/lubridate/wday.qmd">wday()</a></li>
<li><a href="packages/lubridate/qday.qmd">qday()</a></li>
<li><a href="packages/lubridate/yday.qmd">yday()</a></li>
<li><a href="packages/lubridate/day<-.qmd">day&lt;-()</a></li>
<li><a href="packages/lubridate/mday<-.qmd">mday&lt;-()</a></li>
<li><a href="packages/lubridate/qday<-.qmd">qday&lt;-()</a></li>
<li><a href="packages/lubridate/wday<-.qmd">wday&lt;-()</a></li>
<li><a href="packages/lubridate/yday<-.qmd">yday&lt;-()</a></li>
<li><a href="packages/lubridate/hour.qmd">hour()</a></li>
<li><a href="packages/lubridate/hour<-.qmd">hour&lt;-()</a></li>
<li><a href="packages/lubridate/minute.qmd">minute()</a></li>
<li><a href="packages/lubridate/minute<-.qmd">minute&lt;-()</a></li>
<li><a href="packages/lubridate/second.qmd">second()</a></li>
<li><a href="packages/lubridate/second<-.qmd">second&lt;-()</a></li>
<li><a href="packages/lubridate/tz.qmd">tz()</a></li>
<li><a href="packages/lubridate/tz<-.qmd">tz&lt;-()</a></li>
<li><a href="packages/lubridate/as_date.qmd">as_date()</a></li>
<li><a href="packages/lubridate/as_datetime.qmd">as_datetime()</a></li>
<li><a href="packages/lubridate/cyclic_encoding.qmd">cyclic_encoding()</a></li>
<li><a href="packages/lubridate/date.qmd">date()</a></li>
<li><a href="packages/lubridate/date<-.qmd">date&lt;-()</a></li>
<li><a href="packages/lubridate/decimal_date.qmd">decimal_date()</a></li>
<li><a href="packages/lubridate/is.Date.qmd">is.Date()</a></li>
<li><a href="packages/lubridate/Date.qmd">Date()</a></li>
<li><a href="packages/lubridate/NA_Date_.qmd">NA_Date_</a></li>
<li><a href="packages/lubridate/is.POSIXt.qmd">is.POSIXt()</a></li>
<li><a href="packages/lubridate/is.POSIXlt.qmd">is.POSIXlt()</a></li>
<li><a href="packages/lubridate/is.POSIXct.qmd">is.POSIXct()</a></li>
<li><a href="packages/lubridate/POSIXct.qmd">POSIXct()</a></li>
<li><a href="packages/lubridate/NA_POSIXct_.qmd">NA_POSIXct_</a></li>
<li><a href="packages/lubridate/is.instant.qmd">is.instant()</a></li>
<li><a href="packages/lubridate/is.timepoint.qmd">is.timepoint()</a></li>
<li><a href="packages/lubridate/make_datetime.qmd">make_datetime()</a></li>
<li><a href="packages/lubridate/make_date.qmd">make_date()</a></li>
<li><a href="packages/lubridate/now.qmd">now()</a></li>
<li><a href="packages/lubridate/today.qmd">today()</a></li>
<li><a href="packages/lubridate/origin.qmd">origin</a></li>
<li><a href="packages/lubridate/duration.qmd">duration()</a></li>
<li><a href="packages/lubridate/dseconds.qmd">dseconds()</a></li>
<li><a href="packages/lubridate/dminutes.qmd">dminutes()</a></li>
<li><a href="packages/lubridate/dhours.qmd">dhours()</a></li>
<li><a href="packages/lubridate/ddays.qmd">ddays()</a></li>
<li><a href="packages/lubridate/dweeks.qmd">dweeks()</a></li>
<li><a href="packages/lubridate/dmonths.qmd">dmonths()</a></li>
<li><a href="packages/lubridate/dyears.qmd">dyears()</a></li>
<li><a href="packages/lubridate/dmilliseconds.qmd">dmilliseconds()</a></li>
<li><a href="packages/lubridate/dmicroseconds.qmd">dmicroseconds()</a></li>
<li><a href="packages/lubridate/dnanoseconds.qmd">dnanoseconds()</a></li>
<li><a href="packages/lubridate/dpicoseconds.qmd">dpicoseconds()</a></li>
<li><a href="packages/lubridate/is.duration.qmd">is.duration()</a></li>
<li><a href="packages/lubridate/is.difftime.qmd">is.difftime()</a></li>
<li><a href="packages/lubridate/make_difftime.qmd">make_difftime()</a></li>
<li><a href="packages/lubridate/as.duration.qmd">as.duration()</a></li>
<li><a href="packages/lubridate/Duration-class.qmd">Duration-class</a></li>
<li><a href="packages/lubridate/durations.qmd">durations</a></li>
<li><a href="packages/lubridate/period.qmd">period()</a></li>
<li><a href="packages/lubridate/is.period.qmd">is.period()</a></li>
<li><a href="packages/lubridate/seconds.qmd">seconds()</a></li>
<li><a href="packages/lubridate/minutes.qmd">minutes()</a></li>
<li><a href="packages/lubridate/hours.qmd">hours()</a></li>
<li><a href="packages/lubridate/days.qmd">days()</a></li>
<li><a href="packages/lubridate/weeks.qmd">weeks()</a></li>
<li><a href="packages/lubridate/years.qmd">years()</a></li>
<li><a href="packages/lubridate/milliseconds.qmd">milliseconds()</a></li>
<li><a href="packages/lubridate/microseconds.qmd">microseconds()</a></li>
<li><a href="packages/lubridate/nanoseconds.qmd">nanoseconds()</a></li>
<li><a href="packages/lubridate/picoseconds.qmd">picoseconds()</a></li>
<li><a href="packages/lubridate/months.qmd">months()</a></li>
<li><a href="packages/lubridate/period_to_seconds.qmd">period_to_seconds()</a></li>
<li><a href="packages/lubridate/seconds_to_period.qmd">seconds_to_period()</a></li>
<li><a href="packages/lubridate/as.period.qmd">as.period()</a></li>
<li><a href="packages/lubridate/Period-class.qmd">Period-class</a></li>
<li><a href="packages/lubridate/interval.qmd">interval()</a></li>
<li><a href="packages/lubridate/%--%.qmd">%--%</a></li>
<li><a href="packages/lubridate/is.interval.qmd">is.interval()</a></li>
<li><a href="packages/lubridate/int_start.qmd">int_start()</a></li>
<li><a href="packages/lubridate/int_start<-.qmd">int_start&lt;-()</a></li>
<li><a href="packages/lubridate/int_end.qmd">int_end()</a></li>
<li><a href="packages/lubridate/int_end<-.qmd">int_end&lt;-()</a></li>
<li><a href="packages/lubridate/int_length.qmd">int_length()</a></li>
<li><a href="packages/lubridate/int_flip.qmd">int_flip()</a></li>
<li><a href="packages/lubridate/int_shift.qmd">int_shift()</a></li>
<li><a href="packages/lubridate/int_overlaps.qmd">int_overlaps()</a></li>
<li><a href="packages/lubridate/int_standardize.qmd">int_standardize()</a></li>
<li><a href="packages/lubridate/int_aligns.qmd">int_aligns()</a></li>
<li><a href="packages/lubridate/int_diff.qmd">int_diff()</a></li>
<li><a href="packages/lubridate/as.interval.qmd">as.interval()</a></li>
<li><a href="packages/lubridate/%within%.qmd">%within%</a></li>
<li><a href="packages/lubridate/Interval-class.qmd">Interval-class</a></li>
<li><a href="packages/lubridate/intervals.qmd">intervals</a></li>
<li><a href="packages/lubridate/timespan.qmd">timespan</a></li>
<li><a href="packages/lubridate/timespans.qmd">timespans</a></li>
<li><a href="packages/lubridate/time_length.qmd">time_length()</a></li>
<li><a href="packages/lubridate/is.timespan.qmd">is.timespan()</a></li>
<li><a href="packages/lubridate/stamp.qmd">stamp()</a></li>
<li><a href="packages/lubridate/stamp_date.qmd">stamp_date()</a></li>
<li><a href="packages/lubridate/stamp_time.qmd">stamp_time()</a></li>
<li><a href="packages/lubridate/format_ISO8601.qmd">format_ISO8601()</a></li>
<li><a href="packages/lubridate/update.qmd">update()</a></li>
<li><a href="packages/lubridate/fit_to_timeline.qmd">fit_to_timeline()</a></li>
<li><a href="packages/lubridate/with_tz.qmd">with_tz()</a></li>
<li><a href="packages/lubridate/force_tz.qmd">force_tz()</a></li>
<li><a href="packages/lubridate/force_tzs.qmd">force_tzs()</a></li>
<li><a href="packages/lubridate/round_date.qmd">round_date()</a></li>
<li><a href="packages/lubridate/floor_date.qmd">floor_date()</a></li>
<li><a href="packages/lubridate/ceiling_date.qmd">ceiling_date()</a></li>
<li><a href="packages/lubridate/pretty_dates.qmd">pretty_dates()</a></li>
<li><a href="packages/lubridate/rollbackward.qmd">rollbackward()</a></li>
<li><a href="packages/lubridate/rollback.qmd">rollback()</a></li>
<li><a href="packages/lubridate/rollforward.qmd">rollforward()</a></li>
<li><a href="packages/lubridate/%m+%.qmd">%m+%</a></li>
<li><a href="packages/lubridate/add_with_rollback.qmd">add_with_rollback()</a></li>
<li><a href="packages/lubridate/local_time.qmd">local_time()</a></li>
<li><a href="packages/lubridate/am.qmd">am()</a></li>
<li><a href="packages/lubridate/pm.qmd">pm()</a></li>
<li><a href="packages/lubridate/days_in_month.qmd">days_in_month()</a></li>
<li><a href="packages/lubridate/dst.qmd">dst()</a></li>
<li><a href="packages/lubridate/leap_year.qmd">leap_year()</a></li>
<li><a href="packages/lubridate/date_decimal.qmd">date_decimal()</a></li>
<li><a href="packages/lubridate/lakers.qmd">lakers</a></li>
</ul>

</div>
</div>
:::

:::

