---
pagetitle: Aprende Tidyverse
lang: "es"
toc: false
page-layout: full
---

<h1><span class="nombre-resaltado">Cursos Avanzados</span></h1>

Cada curso cuesta $99 USD y dura 6 semanas completas. Por este precio, tendrás acceso a todas las clases en vivo y podrás participar en las sesiones semanales de consulta donde resolveremos sus dudas personalmente.

Lo mejor es que no solo estás aprendiendo algo valioso para ti, sino que también estás ayudando a otros: parte de lo que pagas se destina a crear contenido gratuito para personas que no pueden permitirse estos cursos.

<br>

::: {.grid}

::: {.g-col-12 .g-col-md-6}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>Visualización de datos con R</h3>
<p class="card-text">Inicie en el mundo de R desde cero en este curso de 6 semanas <strong>totalmente gratis</strong>, clases en vivo (Zoom) y sesiones de práctica.</p>
<div style="margin-top: auto;"><a href="courses/fundamentos_R.qmd" class="card-link heading-font">Ver el temario</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-6}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<h3>Limpieza y manipulación de datos</h3>
<p class="card-text">Si desea avanzar en su aprendizaje, puede tomar cursos a un precio accesible con clases en vivo y tutorías individuales.</p>
<div style="margin-top: auto;"><a href="posts.qmd" class="card-link second-color-link heading-font">Ver el temario</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-6}
<div class="card h-100" id="card-second-color">
<div class="card-body d-flex flex-column">
<h3>Introducción a SQL</h3>
<p class="card-text">Una forma de aprender a su ritmo es con nuestra serie de tutoriales, ejemplos concretos de cómo resolver problemas comunes.</p>
<div style="margin-top: auto;"><a href="talks.qmd" class="card-link third-color-link heading-font">Ver el temario</a></div>
</div>
</div>
:::

::: {.g-col-12 .g-col-md-6}
<div class="card h-100" id="card-first-color">
<div class="card-body d-flex flex-column">
<h3>Web Scraping con R</h3>
<p class="card-text">Este es un experimento, pero nuestro objetivo es grabar ejemplos en video para todas las funciones de los paquetes del tidyverse, explicando su uso y cómo se relacionan entre ellas.</p>
<div style="margin-top: auto;"><a href="packages.qmd" class="card-link second-color-link heading-font">Ver el temario</a></div>
</div>
</div>
:::

:::
